### ISSUE TITLE
Missing repository2-2.xml and repository2-3.xml

### ISSUE THREAD

**Issue by isral** [eagletmt/android-repository-history#2]
Missing repository2-2.xml and repository2-3.xml.
Maybe the downloader need to be updated..
Thanks.

**Comment by eagletmt** [comment]
Added in https://github.com/eagletmt/android-repository-history/commit/b464b750a61e5353a0a594a11597392e49a30874 (and https://github.com/eagletmt/android-repository-history/commit/da2474c5991c200b5cc1dc312a80396b8f1aac3a )

**Comment by isral** [comment]
How do you get these URLs? 
In old Android SDK, I can see the URL from SDK Manager's log.

**Comment by eagletmt** [comment]
I found those URLs from sdkmanager's source code.
https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-main/sdklib/src/main/java/com/android/sdklib/repository/AndroidSdkHandler.java
